export const AnubisConfig = {
    executes : {
        execute_1 : {
            name: "B-Execute",
            videoIds : {
                videoId1: "RmnWOZ9TOtE",
                videoId2: "f3ir1gtOCM0",
                videoId3: "x4ukO5sO-Dg",
                videoId4: "08zPWicLARE",
                videoId5: "XbwMkafmsXw",
                videoId6: "XAsdYIsMh_s",
                videoId7: "g2TKZuZxOr8",
                videoId8: "6dqkVZtBBnM",
                videoId9: "hidden",
                videoId10: "hidden"
            },
        },
        execute_2 : {
            name: "A-Execute",
            videoIds : {
                videoId1: "KuWVzUevexw",
                videoId2: "FHnIiZdiHaw",
                videoId3: "nAIMiGfpjCU",
                videoId4: "bmYN0grZ3SY",
                videoId5: "hidden",
                videoId6: "hidden",
                videoId7: "hidden",
                videoId8: "hidden",
                videoId9: "hidden",
                videoId10: "hidden"
            },
        },
        execute_3 : {
            name: "hidden",
            videoIds : {
                videoId1: "hidden",
                videoId2: "hidden",
                videoId3: "hidden",
                videoId4: "hidden",
                videoId5: "hidden",
                videoId6: "hidden",
                videoId7: "hidden",
                videoId8: "hidden",
                videoId9: "hidden",
                videoId10: "hidden"
            },
        },
        execute_4 : {
            name: "hidden",
            videoIds : {
                videoId1: "hidden",
                videoId2: "hidden",
                videoId3: "hidden",
                videoId4: "hidden",
                videoId5: "hidden",
                videoId6: "hidden",
                videoId7: "hidden",
                videoId8: "hidden",
                videoId9: "hidden",
                videoId10: "hidden"
            },
        },
        execute_5 : {
            name: "hidden",
            videoIds : {
                videoId1: "hidden",
                videoId2: "hidden",
                videoId3: "hidden",
                videoId4: "hidden",
                videoId5: "hidden",
                videoId6: "hidden",
                videoId7: "hidden",
                videoId8: "hidden",
                videoId9: "hidden",
                videoId10: "hidden"
            },
        },
    },
    T : {
        videoIds : {
            videoId1: "f3ir1gtOCM0",
            videoId2: "kqzMwvnUtuo",
            videoId3: "lhwI9l9woT8",
            videoId4: "x4ukO5sO-Dg",
            videoId5: "XAsdYIsMh_s",
            videoId6: "08zPWicLARE",
            videoId7: "FHnIiZdiHaw",
            videoId8: "nAIMiGfpjCU",
            videoId9: "bmYN0grZ3SY",
            videoId10: "XbwMkafmsXw",
            videoId11: "g2TKZuZxOr8",
            videoId12: "6dqkVZtBBnM",
            videoId13: "hidden",
            videoId14: "hidden",
            videoId15: "hidden",
            videoId16: "hidden",
            videoId17: "hidden",
            videoId18: "hidden",
            videoId19: "hidden",
            videoId20: "hidden",
            videoId21: "hidden",
            videoId22: "hidden",
            videoId23: "hidden",
            videoId24: "hidden",
            videoId25: "hidden",
            videoId26: "hidden",
            videoId27: "hidden",
            videoId28: "hidden",
            videoId29: "hidden",
            videoId30: "hidden"
        }
    },
    CT : {
        videoIds : {
            videoId1: "vSNYXp3vafs",
            videoId2: "18poQI4S5Mk",
            videoId3: "69eBQdaA7yE",
            videoId4: "hidden",
            videoId5: "hidden",
            videoId6: "hidden",
            videoId7: "hidden",
            videoId8: "hidden",
            videoId9: "hidden",
            videoId10: "hidden",
            videoId11: "hidden",
            videoId12: "hidden",
            videoId13: "hidden",
            videoId14: "hidden",
            videoId15: "hidden",
            videoId16: "hidden",
            videoId17: "hidden",
            videoId18: "hidden",
            videoId19: "hidden",
            videoId20: "hidden",
            videoId21: "hidden",
            videoId22: "hidden",
            videoId23: "hidden",
            videoId24: "hidden",
            videoId25: "hidden",
            videoId26: "hidden",
            videoId27: "hidden",
            videoId28: "hidden",
            videoId29: "hidden",
            videoId30: "hidden"
        }
    }
};