export const Dust2Config = {
    executes : {
        execute_1 : {
            name: "hidden",
            videoIds : {
                videoId1: "hidden",
                videoId2: "hidden",
                videoId3: "hidden",
                videoId4: "hidden",
                videoId5: "hidden",
                videoId6: "hidden",
                videoId7: "hidden",
                videoId8: "hidden",
                videoId9: "hidden",
                videoId10: "hidden"
            },
        },
        execute_2 : {
            name: "hidden",
            videoIds : {
                videoId1: "hidden",
                videoId2: "hidden",
                videoId3: "hidden",
                videoId4: "hidden",
                videoId5: "hidden",
                videoId6: "hidden",
                videoId7: "hidden",
                videoId8: "hidden",
                videoId9: "hidden",
                videoId10: "hidden"
            },
        },
        execute_3 : {
            name: "hidden",
            videoIds : {
                videoId1: "hidden",
                videoId2: "hidden",
                videoId3: "hidden",
                videoId4: "hidden",
                videoId5: "hidden",
                videoId6: "hidden",
                videoId7: "hidden",
                videoId8: "hidden",
                videoId9: "hidden",
                videoId10: "hidden"
            },
        },
        execute_4 : {
            name: "hidden",
            videoIds : {
                videoId1: "hidden",
                videoId2: "hidden",
                videoId3: "hidden",
                videoId4: "hidden",
                videoId5: "hidden",
                videoId6: "hidden",
                videoId7: "hidden",
                videoId8: "hidden",
                videoId9: "hidden",
                videoId10: "hidden"
            },
        },
        execute_5 : {
            name: "hidden",
            videoIds : {
                videoId1: "hidden",
                videoId2: "hidden",
                videoId3: "hidden",
                videoId4: "hidden",
                videoId5: "hidden",
                videoId6: "hidden",
                videoId7: "hidden",
                videoId8: "hidden",
                videoId9: "hidden",
                videoId10: "hidden"
            },
        },
    },
    T : {
        videoIds : {
            videoId1: "jUVW6O3xnlQ",
            videoId2: "4GAKlB0boPE",
            videoId3: "lT08AowXyeI",
            videoId4: "PQzyyEoPDDw",
            videoId5: "fHTebGHe54s",
            videoId6: "n0eNKn9b1D4",
            videoId7: "JRjxazXFPso",
            videoId8: "hidden",
            videoId9: "hidden",
            videoId10: "hidden",
            videoId11: "hidden",
            videoId12: "hidden",
            videoId13: "hidden",
            videoId14: "hidden",
            videoId15: "hidden",
            videoId16: "hidden",
            videoId17: "hidden",
            videoId18: "hidden",
            videoId19: "hidden",
            videoId20: "hidden",
            videoId21: "hidden",
            videoId22: "hidden",
            videoId23: "hidden",
            videoId24: "hidden",
            videoId25: "hidden",
            videoId26: "hidden",
            videoId27: "hidden",
            videoId28: "hidden",
            videoId29: "hidden",
            videoId30: "hidden"
        }
    },
    CT : {
        videoIds : {
            videoId1: "iqckp6saP9A",
            videoId2: "lx3sH9EbrQM",
            videoId3: "hidden",
            videoId4: "hidden",
            videoId5: "hidden",
            videoId6: "hidden",
            videoId7: "hidden",
            videoId8: "hidden",
            videoId9: "hidden",
            videoId10: "hidden",
            videoId11: "hidden",
            videoId12: "hidden",
            videoId13: "hidden",
            videoId14: "hidden",
            videoId15: "hidden",
            videoId16: "hidden",
            videoId17: "hidden",
            videoId18: "hidden",
            videoId19: "hidden",
            videoId20: "hidden",
            videoId21: "hidden",
            videoId22: "hidden",
            videoId23: "hidden",
            videoId24: "hidden",
            videoId25: "hidden",
            videoId26: "hidden",
            videoId27: "hidden",
            videoId28: "hidden",
            videoId29: "hidden",
            videoId30: "hidden"
        }
    }
};