export const InfernoConfig = {
    executes : {
        execute_1 : {
            name: "A-Execute",
            videoIds : {
                videoId1: "2pFk-FUGnZA",
                videoId2: "B50IZFbF5sM",
                videoId3: "i9gfPBI5Rcc",
                videoId4: "7NNjogh3Xqg",
                videoId5: "roOdCWvYpGk",
                videoId6: "hidden",
                videoId7: "hidden",
                videoId8: "hidden",
                videoId9: "hidden",
                videoId10: "hidden"
            },
        },
        execute_2 : {
            name: "B-Execute",
            videoIds : {
                videoId1: "ARouTAHEkks",
                videoId2: "ymWPO7168kM",
                videoId3: "tssLy8l8810",
                videoId4: "3muJxeE5wW0",
                videoId5: "dKELveVS-BY",
                videoId6: "STAXDITg5kY",
                videoId7: "hidden",
                videoId8: "hidden",
                videoId9: "hidden",
                videoId10: "hidden"
            },
        },
        execute_3 : {
            name: "hidden",
            videoIds : {
                videoId1: "hidden",
                videoId2: "hidden",
                videoId3: "hidden",
                videoId4: "hidden",
                videoId5: "hidden",
                videoId6: "hidden",
                videoId7: "hidden",
                videoId8: "hidden",
                videoId9: "hidden",
                videoId10: "hidden"
            },
        },
        execute_4 : {
            name: "hidden",
            videoIds : {
                videoId1: "hidden",
                videoId2: "hidden",
                videoId3: "hidden",
                videoId4: "hidden",
                videoId5: "hidden",
                videoId6: "hidden",
                videoId7: "hidden",
                videoId8: "hidden",
                videoId9: "hidden",
                videoId10: "hidden"
            },
        },
        execute_5 : {
            name: "hidden",
            videoIds : {
                videoId1: "hidden",
                videoId2: "hidden",
                videoId3: "hidden",
                videoId4: "hidden",
                videoId5: "hidden",
                videoId6: "hidden",
                videoId7: "hidden",
                videoId8: "hidden",
                videoId9: "hidden",
                videoId10: "hidden"
            },
        },
    },
    T : {
        videoIds : {
            videoId1: "B50IZFbF5sM",
            videoId2: "i9gfPBI5Rcc",
            videoId3: "7NNjogh3Xqg",
            videoId4: "roOdCWvYpGk",
            videoId5: "Df3Eh1nL2zw",
            videoId6: "ymWPO7168kM",
            videoId7: "tssLy8l8810",
            videoId8: "STAXDITg5kY",
            videoId9: "dKELveVS-BY",
            videoId10: "3muJxeE5wW0",
            videoId11: "Qr8cNUfaUUw",
            videoId12: "OFtWJRc-RUg",
            videoId13: "r-TOT86EOF0",
            videoId14: "EtlgxbeeUBE",
            videoId15: "hidden",
            videoId16: "hidden",
            videoId17: "hidden",
            videoId18: "hidden",
            videoId19: "hidden",
            videoId20: "hidden",
            videoId21: "hidden",
            videoId22: "hidden",
            videoId23: "hidden",
            videoId24: "hidden",
            videoId25: "hidden",
            videoId26: "hidden",
            videoId27: "hidden",
            videoId28: "hidden",
            videoId29: "hidden",
            videoId30: "hidden"
        }
    },
    CT : {
        videoIds : {
            videoId1: "nGwL_iZ597o",
            videoId2: "81DkJ6MRESw",
            videoId3: "phm6X9jIiP4",
            videoId4: "LQ75JqDZqjU",
            videoId5: "hidden",
            videoId6: "hidden",
            videoId7: "hidden",
            videoId8: "hidden",
            videoId9: "hidden",
            videoId10: "hidden",
            videoId11: "hidden",
            videoId12: "hidden",
            videoId13: "hidden",
            videoId14: "hidden",
            videoId15: "hidden",
            videoId16: "hidden",
            videoId17: "hidden",
            videoId18: "hidden",
            videoId19: "hidden",
            videoId20: "hidden",
            videoId21: "hidden",
            videoId22: "hidden",
            videoId23: "hidden",
            videoId24: "hidden",
            videoId25: "hidden",
            videoId26: "hidden",
            videoId27: "hidden",
            videoId28: "hidden",
            videoId29: "hidden",
            videoId30: "hidden"
        }
    }
};