export const MirageConfig = {
    executes : {
        execute_1 : {
            name: "A",
            videoIds : {
                videoId1: "fixAExecute",
                videoId2: "kj3Koblbt3s",
                videoId3: "jJ9L1_Pl3uo",
                videoId4: "x4VHHS2HtlQ",
                videoId5: "yd2UHpn3xl0",
                videoId6: "FOfG55xswsM",
                videoId7: "f7QQUCLhAlA",
                videoId8: "iLv1JRjI3Ic",
                videoId9: "iTjelxItrkQ",
                videoId10: "hidden"
            },
        },
        execute_2 : {
            name: "B",
            videoIds : {
                videoId1: "fixBExecute",
                videoId2: "39hFNZJ-y7Y",
                videoId3: "RR0Vgb7rizM",
                videoId4: "2DZORFSIaBQ",
                videoId5: "kBSybnwO8VI",
                videoId6: "YOL6OB4PaGM",
                videoId7: "2bYRveNCcdQ",
                videoId8: "Cjar3FHvO6g",
                videoId9: "hidden",
                videoId10: "hidden"
            },
        },
        execute_3 : {
            name: "Mid",
            videoIds : {
                videoId1: "T9KAOFbJzp4",
                videoId2: "iTjelxItrkQ",
                videoId3: "KgFYD4roW_8",
                videoId4: "zFJN4LJH2G4",
                videoId5: "d7hZfOTw18E",
                videoId6: "zA-CGZVTiXw",
                videoId7: "51O2KXJZZoE",
                videoId8: "ZLxzxRQFYl4",
                videoId9: "hidden",
                videoId10: "hidden"
            },
        },
        execute_4 : {
            name: "hidden",
            videoIds : {
                videoId1: "hidden",
                videoId2: "hidden",
                videoId3: "hidden",
                videoId4: "hidden",
                videoId5: "hidden",
                videoId6: "hidden",
                videoId7: "hidden",
                videoId8: "hidden",
                videoId9: "hidden",
                videoId10: "hidden"
            },
        },
        execute_5 : {
            name: "hidden",
            videoIds : {
                videoId1: "hidden",
                videoId2: "hidden",
                videoId3: "hidden",
                videoId4: "hidden",
                videoId5: "hidden",
                videoId6: "hidden",
                videoId7: "hidden",
                videoId8: "hidden",
                videoId9: "hidden",
                videoId10: "hidden"
            },
        },
    },
    T : {
        videoIds : {
            videoId1: "x4VHHS2HtlQ",
            videoId2: "jJ9L1_Pl3uo",
            videoId3: "yd2UHpn3xl0",
            videoId4: "f7QQUCLhAlA",
            videoId5: "iLv1JRjI3Ic",
            videoId6: "FOfG55xswsM",
            videoId7: "kj3Koblbt3s",
            videoId8: "kBSybnwO8VI",
            videoId9: "RR0Vgb7rizM",
            videoId10: "YPuaH6gr5oI",
            videoId11: "YOL6OB4PaGM",
            videoId12: "39hFNZJ-y7Y",
            videoId13: "2DZORFSIaBQ",
            videoId14: "2bYRveNCcdQ",
            videoId15: "Cjar3FHvO6g",
            videoId16: "iTjelxItrkQ",
            videoId17: "d7hZfOTw18E",
            videoId18: "KgFYD4roW_8",
            videoId19: "ZLxzxRQFYl4",
            videoId20: "zA-CGZVTiXw",
            videoId21: "51O2KXJZZoE",
            videoId22: "zFJN4LJH2G4",
            videoId23: "hidden",
            videoId24: "hidden",
            videoId25: "hidden",
            videoId26: "hidden",
            videoId27: "hidden",
            videoId28: "hidden",
            videoId29: "hidden",
            videoId30: "hidden"
        }
    },
    CT : {
        videoIds : {
            videoId1: "P4b4q0DHXoE",
            videoId2: "2sdVi78Blq0",
            videoId3: "kHCHdBH9Atk",
            videoId4: "PY1hbWH_t6w",
            videoId5: "wvU333UtUTQ",
            videoId6: "GkmyAYjwHXE",
            videoId7: "A70WypTrP-0",
            videoId8: "hidden",
            videoId9: "hidden",
            videoId10: "hidden",
            videoId11: "hidden",
            videoId12: "hidden",
            videoId13: "hidden",
            videoId14: "hidden",
            videoId15: "hidden",
            videoId16: "hidden",
            videoId17: "hidden",
            videoId18: "hidden",
            videoId19: "hidden",
            videoId20: "hidden",
            videoId21: "hidden",
            videoId22: "hidden",
            videoId23: "hidden",
            videoId24: "hidden",
            videoId25: "hidden",
            videoId26: "hidden",
            videoId27: "hidden",
            videoId28: "hidden",
            videoId29: "hidden",
            videoId30: "hidden"
        }
    }
};