export const NukeConfig = {
    executes : {
        execute_1 : {
            name: "A",
            videoIds : {
                videoId1: "0n9ZTvoVsI0",
                videoId2: "473fxB4-4Hs",
                videoId3: "w-fue6Brrws",
                videoId4: "O9L2y3zpTNY",
                videoId5: "EvtjfTOcF5c",
                videoId6: "hidden",
                videoId7: "hidden",
                videoId8: "hidden",
                videoId9: "hidden",
                videoId10: "hidden"
            },
        },
        execute_2 : {
            name: "Ramp",
            videoIds : {
                videoId1: "-A69ZzHE44I",
                videoId2: "CuMYlnLbALA",
                videoId3: "Zvo3Y8i1AJo",
                videoId4: "KYnal__6byk",
                videoId5: "hidden",
                videoId6: "hidden",
                videoId7: "hidden",
                videoId8: "hidden",
                videoId9: "hidden",
                videoId10: "hidden"
            },
        },
        execute_3 : {
            name: "hidden",
            videoIds : {
                videoId1: "hidden",
                videoId2: "hidden",
                videoId3: "hidden",
                videoId4: "hidden",
                videoId5: "hidden",
                videoId6: "hidden",
                videoId7: "hidden",
                videoId8: "hidden",
                videoId9: "hidden",
                videoId10: "hidden"
            },
        },
        execute_4 : {
            name: "hidden",
            videoIds : {
                videoId1: "hidden",
                videoId2: "hidden",
                videoId3: "hidden",
                videoId4: "hidden",
                videoId5: "hidden",
                videoId6: "hidden",
                videoId7: "hidden",
                videoId8: "hidden",
                videoId9: "hidden",
                videoId10: "hidden"
            },
        },
        execute_5 : {
            name: "hidden",
            videoIds : {
                videoId1: "hidden",
                videoId2: "hidden",
                videoId3: "hidden",
                videoId4: "hidden",
                videoId5: "hidden",
                videoId6: "hidden",
                videoId7: "hidden",
                videoId8: "hidden",
                videoId9: "hidden",
                videoId10: "hidden"
            },
        },
    },
    T : {
        videoIds : {
            videoId1: "hwXNF2FHGSo",
            videoId2: "THstLeP_DLY",
            videoId3: "hUYHDO55oAY",
            videoId4: "473fxB4-4Hs",
            videoId5: "QrqST_-eCZQ",
            videoId6: "CuMYlnLbALA",
            videoId7: "KYnal__6byk",
            videoId8: "Zvo3Y8i1AJo",
            videoId9: "wtw4ZBAdgRI",
            videoId10: "O9L2y3zpTNY",
            videoId11: "EvtjfTOcF5c",
            videoId12: "w-fue6Brrws",
            videoId13: "22F0Gko4hsI",
            videoId14: "hidden",
            videoId15: "hidden",
            videoId16: "hidden",
            videoId17: "hidden",
            videoId18: "hidden",
            videoId19: "hidden",
            videoId20: "hidden",
            videoId21: "hidden",
            videoId22: "hidden",
            videoId23: "hidden",
            videoId24: "hidden",
            videoId25: "hidden",
            videoId26: "hidden",
            videoId27: "hidden",
            videoId28: "hidden",
            videoId29: "hidden",
            videoId30: "hidden"
        }
    },
    CT : {
        videoIds : {
            videoId1: "IAOGZT9DvLY",
            videoId2: "wNA8BHxquAY",
            videoId3: "6_LixYSStHQ",
            videoId4: "GY1dDjyU6bY",
            videoId5: "hidden",
            videoId6: "hidden",
            videoId7: "hidden",
            videoId8: "hidden",
            videoId9: "hidden",
            videoId10: "hidden",
            videoId11: "hidden",
            videoId12: "hidden",
            videoId13: "hidden",
            videoId14: "hidden",
            videoId15: "hidden",
            videoId16: "hidden",
            videoId17: "hidden",
            videoId18: "hidden",
            videoId19: "hidden",
            videoId20: "hidden",
            videoId21: "hidden",
            videoId22: "hidden",
            videoId23: "hidden",
            videoId24: "hidden",
            videoId25: "hidden",
            videoId26: "hidden",
            videoId27: "hidden",
            videoId28: "hidden",
            videoId29: "hidden",
            videoId30: "hidden"
        }
    }
};