export const VertigoConfig = {
    executes : {
        execute_1 : {
            name: "A",
            videoIds : {
                videoId1: "OWiXEilotW0",
                videoId2: "2m9DQka5IF8",
                videoId3: "y-C2oILeeH4",
                videoId4: "T-Isaq_CjMg",
                videoId5: "hidden",
                videoId6: "hidden",
                videoId7: "hidden",
                videoId8: "hidden",
                videoId9: "hidden",
                videoId10: "hidden"
            },
        },
        execute_2 : {
            name: "hidden",
            videoIds : {
                videoId1: "hidden",
                videoId2: "hidden",
                videoId3: "hidden",
                videoId4: "hidden",
                videoId5: "hidden",
                videoId6: "hidden",
                videoId7: "hidden",
                videoId8: "hidden",
                videoId9: "hidden",
                videoId10: "hidden"
            },
        },
        execute_3 : {
            name: "hidden",
            videoIds : {
                videoId1: "hidden",
                videoId2: "hidden",
                videoId3: "hidden",
                videoId4: "hidden",
                videoId5: "hidden",
                videoId6: "hidden",
                videoId7: "hidden",
                videoId8: "hidden",
                videoId9: "hidden",
                videoId10: "hidden"
            },
        },
        execute_4 : {
            name: "hidden",
            videoIds : {
                videoId1: "hidden",
                videoId2: "hidden",
                videoId3: "hidden",
                videoId4: "hidden",
                videoId5: "hidden",
                videoId6: "hidden",
                videoId7: "hidden",
                videoId8: "hidden",
                videoId9: "hidden",
                videoId10: "hidden"
            },
        },
        execute_5 : {
            name: "hidden",
            videoIds : {
                videoId1: "hidden",
                videoId2: "hidden",
                videoId3: "hidden",
                videoId4: "hidden",
                videoId5: "hidden",
                videoId6: "hidden",
                videoId7: "hidden",
                videoId8: "hidden",
                videoId9: "hidden",
                videoId10: "hidden"
            },
        },
    },
    T : {
        videoIds : {
            videoId1: "2m9DQka5IF8",
            videoId2: "y-C2oILeeH4",
            videoId3: "T-Isaq_CjMg",
            videoId4: "VGpLvvJSSRM",
            videoId5: "yEsDniOAze8",
            videoId6: "XswIsZRpLCg",
            videoId7: "271QrHUVnCs",
            videoId8: "XeRrgjbfT-A",
            videoId9: "fFaIeFUwujE",
            videoId10: "s2Uk9YQgmQg",
            videoId11: "hidden",
            videoId12: "hidden",
            videoId13: "hidden",
            videoId14: "hidden",
            videoId15: "hidden",
            videoId16: "hidden",
            videoId17: "hidden",
            videoId18: "hidden",
            videoId19: "hidden",
            videoId20: "hidden",
            videoId21: "hidden",
            videoId22: "hidden",
            videoId23: "hidden",
            videoId24: "hidden",
            videoId25: "hidden",
            videoId26: "hidden",
            videoId27: "hidden",
            videoId28: "hidden",
            videoId29: "hidden",
            videoId30: "hidden"
        }
    },
    CT : {
        videoIds : {
            videoId1: "ABp1tyExD1Y",
            videoId2: "cN3M6edSidI",
            videoId3: "CKslL3rqiZc",
            videoId4: "s2Uk9YQgmQg",
            videoId5: "hidden",
            videoId6: "hidden",
            videoId7: "hidden",
            videoId8: "hidden",
            videoId9: "hidden",
            videoId10: "hidden",
            videoId11: "hidden",
            videoId12: "hidden",
            videoId13: "hidden",
            videoId14: "hidden",
            videoId15: "hidden",
            videoId16: "hidden",
            videoId17: "hidden",
            videoId18: "hidden",
            videoId19: "hidden",
            videoId20: "hidden",
            videoId21: "hidden",
            videoId22: "hidden",
            videoId23: "hidden",
            videoId24: "hidden",
            videoId25: "hidden",
            videoId26: "hidden",
            videoId27: "hidden",
            videoId28: "hidden",
            videoId29: "hidden",
            videoId30: "hidden"
        }
    }
};